on:
  pull_request:

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-env
        with:
          gcp_workload_identity_provider: ${{ secrets.GCP_STREAMX_RELEASES_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: ${{ secrets.GCP_STREAMX_RELEASES_RELEASE_DEPLOY_SA }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test and build JAR
        run: |
          .github/scripts/with-capture-docker-logs.sh ./mvnw verify -Pci

      - name: Upload test reports
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Test report - build ${{ matrix.name }}

      - name: Upload Docker logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs-${{ matrix.name }}
          path: target/docker-logs/
          if-no-files-found: ignore