name: Trigger release

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - preview

permissions:
  contents: write

jobs:
  trigger-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
          token: ${{ steps.app-token.outputs.token }}

      - uses: ./.github/actions/setup-env
        with:
          github_token: ${{ steps.app-token.outputs.token }}

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Run release
        run: ./.github/scripts/release.sh ${{ inputs.type }} -y